// Published v1 SQL remains unchanged; this migration is atomic and repeatable.
export const migration2 = `
ALTER TABLE resource_categories RENAME TO courses;
ALTER TABLE resources RENAME COLUMN category_id TO course_id;
ALTER TABLE resources ADD COLUMN original_name TEXT;
UPDATE resources SET original_name=(SELECT original_name FROM attachments WHERE id=attachment_id) WHERE kind='file';
ALTER TABLE courses ADD COLUMN created_at TEXT NOT NULL DEFAULT '';
ALTER TABLE courses ADD COLUMN sort_order INTEGER NOT NULL DEFAULT 0;
INSERT INTO courses(id,name,normalized_name) VALUES('00000000-0000-4000-8000-000000000001','未归档','未归档') ON CONFLICT(normalized_name) DO NOTHING;
UPDATE resources SET course_id=(SELECT id FROM courses WHERE normalized_name='未归档') WHERE course_id IS NULL;
CREATE TABLE time_conversions(id TEXT PRIMARY KEY,operation_id TEXT UNIQUE NOT NULL,time_ms INTEGER NOT NULL CHECK(time_ms>0),points INTEGER NOT NULL CHECK(points>0 AND time_ms=points*60000),rate_version INTEGER NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE time_entries_next(seq INTEGER PRIMARY KEY AUTOINCREMENT,id TEXT UNIQUE NOT NULL,kind TEXT NOT NULL,amount_ms INTEGER NOT NULL,session_id TEXT REFERENCES study_sessions(id),redemption_id TEXT UNIQUE REFERENCES redemptions(id),session_total_after_ms INTEGER,created_at TEXT NOT NULL,conversion_id TEXT UNIQUE REFERENCES time_conversions(id),CHECK((kind='study' AND amount_ms>0 AND session_id IS NOT NULL AND redemption_id IS NULL AND conversion_id IS NULL) OR (kind='redeem' AND amount_ms<0 AND session_id IS NULL AND redemption_id IS NOT NULL AND conversion_id IS NULL) OR (kind='conversion' AND amount_ms<0 AND session_id IS NULL AND redemption_id IS NULL AND conversion_id IS NOT NULL)));
INSERT INTO time_entries_next(seq,id,kind,amount_ms,session_id,session_total_after_ms,created_at) SELECT MIN(seq),MIN(id),'study',SUM(amount_ms),session_id,SUM(amount_ms),MIN(created_at) FROM time_entries WHERE kind='study' GROUP BY session_id;
INSERT INTO time_entries_next(seq,id,kind,amount_ms,redemption_id,created_at) SELECT seq,id,kind,amount_ms,redemption_id,created_at FROM time_entries WHERE kind!='study';
CREATE TABLE study_day_slices_next(entry_id TEXT NOT NULL REFERENCES time_entries_next(id),local_date TEXT NOT NULL,timezone TEXT NOT NULL DEFAULT 'Asia/Shanghai',amount_ms INTEGER NOT NULL CHECK(amount_ms>0),PRIMARY KEY(entry_id,local_date,timezone));
INSERT INTO study_day_slices_next SELECT n.id,d.local_date,d.timezone,SUM(d.amount_ms) FROM study_day_slices d JOIN time_entries e ON e.id=d.entry_id JOIN time_entries_next n ON n.session_id=e.session_id GROUP BY n.id,d.local_date,d.timezone;
DROP TABLE study_day_slices;
DROP TABLE time_entries;
ALTER TABLE time_entries_next RENAME TO time_entries;
ALTER TABLE study_day_slices_next RENAME TO study_day_slices;
CREATE UNIQUE INDEX income_per_session ON time_entries(session_id) WHERE kind='study';
CREATE INDEX daily_date ON study_day_slices(local_date);
ALTER TABLE rewards RENAME COLUMN price_sec TO price_points;
UPDATE rewards SET price_points=(price_points+59)/60;
ALTER TABLE redemption_intents RENAME COLUMN price_sec_snapshot TO price_amount;
ALTER TABLE redemption_intents ADD COLUMN currency TEXT NOT NULL DEFAULT 'study_ms' CHECK(currency IN ('study_ms','points'));
UPDATE redemption_intents SET price_amount=price_amount*1000,state=CASE WHEN state='pending' THEN 'cancelled' ELSE state END;
ALTER TABLE redemptions RENAME COLUMN price_sec_snapshot TO price_amount;
ALTER TABLE redemptions ADD COLUMN currency TEXT NOT NULL DEFAULT 'study_ms' CHECK(currency IN ('study_ms','points'));
UPDATE redemptions SET price_amount=price_amount*1000;
CREATE TABLE collectible_catalog(id TEXT PRIMARY KEY,name TEXT NOT NULL,rarity INTEGER NOT NULL CHECK(rarity BETWEEN 0 AND 5),sell_points INTEGER NOT NULL CHECK(sell_points>0),model TEXT NOT NULL,thumbnail TEXT NOT NULL,asset_version INTEGER NOT NULL);
CREATE TABLE loot_state(id INTEGER PRIMARY KEY CHECK(id=1),sequence INTEGER NOT NULL UNIQUE,target_ms INTEGER NOT NULL CHECK(target_ms BETWEEN 600000 AND 1800000),progress_ms INTEGER NOT NULL CHECK(progress_ms>=0 AND progress_ms<target_ms),catalog_id TEXT NOT NULL REFERENCES collectible_catalog(id),rule_version INTEGER NOT NULL);
CREATE TABLE loot_events(sequence INTEGER PRIMARY KEY,instance_id TEXT UNIQUE NOT NULL,created_at TEXT NOT NULL,rule_version INTEGER NOT NULL);
CREATE TABLE collectible_instances(id TEXT PRIMARY KEY,catalog_id TEXT NOT NULL REFERENCES collectible_catalog(id),rarity_snapshot INTEGER NOT NULL CHECK(rarity_snapshot BETWEEN 0 AND 5),sell_points_snapshot INTEGER NOT NULL CHECK(sell_points_snapshot>0),state TEXT NOT NULL CHECK(state IN ('warehouse','display','sold')),slot_index INTEGER UNIQUE,tank_index INTEGER UNIQUE,drop_event_id INTEGER UNIQUE NOT NULL REFERENCES loot_events(sequence),created_at TEXT NOT NULL,CHECK((state='warehouse' AND slot_index BETWEEN 0 AND 49 AND slot_index IS NOT NULL AND tank_index IS NULL) OR (state='display' AND tank_index BETWEEN 0 AND 5 AND tank_index IS NOT NULL AND slot_index IS NULL) OR (state='sold' AND slot_index IS NULL AND tank_index IS NULL)));
CREATE TABLE business_intents(id TEXT PRIMARY KEY,kind TEXT NOT NULL CHECK(kind IN ('conversion','sale')),payload_json TEXT NOT NULL,amount INTEGER NOT NULL CHECK(amount>0),state TEXT NOT NULL CHECK(state IN ('pending','confirmed')),result_json TEXT);
CREATE TABLE sales(id TEXT PRIMARY KEY,intent_id TEXT UNIQUE NOT NULL REFERENCES business_intents(id),items_json TEXT NOT NULL,points INTEGER NOT NULL CHECK(points>0),created_at TEXT NOT NULL);
CREATE TABLE point_entries(id TEXT PRIMARY KEY,amount INTEGER NOT NULL CHECK(typeof(amount)='integer' AND amount!=0 AND abs(amount)<=8000000000000),kind TEXT NOT NULL,conversion_id TEXT UNIQUE REFERENCES time_conversions(id),sale_id TEXT UNIQUE REFERENCES sales(id),redemption_id TEXT UNIQUE REFERENCES redemptions(id),created_at TEXT NOT NULL,CHECK((kind='conversion' AND amount>0 AND conversion_id IS NOT NULL AND sale_id IS NULL AND redemption_id IS NULL) OR (kind='sale' AND amount>0 AND sale_id IS NOT NULL AND conversion_id IS NULL AND redemption_id IS NULL) OR (kind='purchase' AND amount<0 AND redemption_id IS NOT NULL AND conversion_id IS NULL AND sale_id IS NULL)));
INSERT INTO app_meta VALUES('economy_migration_notice','1');
`;
